/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DropzoneBackground: typeof import('./src/components/DropzoneBackground.vue')['default']
    LeaferNode: typeof import('./src/components/LeaferNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecialEdge: typeof import('./src/components/SpecialEdge.vue')['default']
    SpecialNode: typeof import('./src/components/SpecialNode.vue')['default']
    ToolsPanel: typeof import('./src/components/ToolsPanel.vue')['default']
  }
}

// For TSX support
declare global {
  const DropzoneBackground: typeof import('./src/components/DropzoneBackground.vue')['default']
  const LeaferNode: typeof import('./src/components/LeaferNode.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SpecialEdge: typeof import('./src/components/SpecialEdge.vue')['default']
  const SpecialNode: typeof import('./src/components/SpecialNode.vue')['default']
  const ToolsPanel: typeof import('./src/components/ToolsPanel.vue')['default']
}